### ISSUE TITLE
Send a large bomb from a remote url

### ISSUE THREAD

**Issue by ghost** [Xumeiquer/nobots#3]
Could I send a large bomb file from a remote url?

[Example File](http://repos.lax-noc.com/speedtests/10tb.bin)

**Comment by Xumeiquer** [comment]
Sorry, I didn't see it.

What could benefit that kind of feature?

As I see it, there are two options:
1. Redirect attacker to the bomb endpoint, which means a 30X redirect.
2. Nobots will download the bomb from the remote location, store it locally and serve it locally as well. In this case the feature loses its meaning.

Regards,

**Comment by Xumeiquer** [comment]
No answer.
