### ISSUE TITLE
How to load the bomb in Nginx?

### ISSUE THREAD

**Issue by Jinnrry** [Xumeiquer/nobots#7]
I try load the bomb file in Nginx.
The is my config

        location ~ (wlwmanifest|sitemap|xmlrpc|config\.php|wp-login|sign_in|execute-solution|wp-admin|eval-stdin\.php) {
           rewrite ^/.* /10G.gzip;
        }
        location = /10G.gzip {
          root /;
          access_log off;
          add_header Content-Encoding gzip;
          gzip off;
          default_type 'text/html';
        }

But I test the bomb in GoLang. The http response body size only 9M. This is my test code

    func main() {
	    resp, _ := http.Get("https://jinnrry.com/10G.gzip")
	    body, _ := ioutil.ReadAll(resp.Body)
    
	    fmt.Println(len(body) / 1024 / 1024) // echo 9
    
    }

If the bomb only zip once. The http response body size get 1G.

**Comment by Jinnrry** [comment]
If the 1G bomb only zip once, the bomb file size is 1M+. It is too large.

**Comment by Xumeiquer** [comment]
I don't have any clue about the Nginx configuration for sending gzip files. On the other hand, this is a project for the Caddy server in particular for a module that can be used in Caddy for stopping bots.
