### ISSUE TITLE
failed with caddy 2.5.0 beta1

### ISSUE THREAD

**Issue by mzhboy** [Xumeiquer/nobots#8]
> run: adapting config using caddyfile: Caddyfile.a:68: unrecognized directive: nobots
start: caddy process exited with error: exit status 1

```config
:port,site.com {
        ....
	nobots "booomb.gz" {
		regexp '.*[Ss]ider.*'
		regexp '.*[Bb]ot.*'
		regexp '.*[Ss]lurp.*'
	}

	root * /var/www/html/
	file_server
        php_fastcgi unix//run/php/php-fpm.sock
        ....
}
```

What's wrong with this caddyfile configuration?

**Comment by Xumeiquer** [comment]
That must be your Caddy version does not include the nobots plugin. I encourage you to download Caddy Server with nobots plugin.
